### PR TITLE
Add tag to image.sc link

### PR DESCRIPTION
**Pull request by joshmoore**

### CODE REVIEW

**Comment by joshmoore** [comment]
@sbesson : should we use `@IDRStatus` for this or should that be deprecated?

**Comment by joshmoore** [comment]
Oh wow. PRs go crazy!

**Comment by sbesson** [comment]
> @sbesson : should we use @IDRStatus for this or should that be deprecated?

Ah good point since we had a dedicated alias. Maybe let's do that for now as we haven't really made the decision to get rid of this.

**Comment by joshmoore** [comment]
Pushed directly.

**Comment by joshmoore** [comment]
I also realized I'm not overly monitoring IDRStatus. Are you, @sbesson ?

**Comment by sbesson** [comment]
> I also realized I'm not overly monitoring IDRStatus. Are you, @sbesson ?

Neither do I. Maybe a case for unifying with IDRnews as mentioned above.

**Pull request closed without merging**
